#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-08-29"
name = "cottonwind-page"
pages_build_output_dir = "./dist"

[vars]
ORIGIN = "https://cottonwind.com"
TITLE = "ã“ã£ã¨ã‚“ã†ãƒã‚“ã©"
VERSION = "4.0.0"

DESCRIPTION = "ã‚ãŸã‹ãœã‚³ã‚¦(@kouwtkz)ã®å€‹äººã‚µã‚¤ãƒˆã€‚æ°—ã¾ãã‚Œã«æ§˜ã€…ãªã‚¤ãƒ©ã‚¹ãƒˆã‚„ä½œå“ã‚’è¼‰ã›ã¦ã¾ã™ã€‚"
OVERVIEW = "ã‚ãŸã‹ãœã‚³ã‚¦ã®å€‹äººã‚µã‚¤ãƒˆ"

ALTERNATE = "ã‚ãŸã‹ãœã‚³ã‚¦,kouwtkz,ã‚ãŸã‹ãœã£ã“,ã‚ãŸã‹ãœãã‚“,ã‚ãŸã‹ãœã‚³ã‚¦ã®å€‹äººã‚µã‚¤ãƒˆ,ã‚ãŸã‹ãœã‚³ã‚¦ã®ãƒãƒ¼ãƒˆãƒ•ã‚©ãƒªã‚ªã‚µã‚¤ãƒˆ"

AUTHOR_ACCOUNT = "kouwtkz"
AUTHOR_NAME = "ã‚ãŸã‹ãœã‚³ã‚¦"

AUTHOR_EN_NAME = "WATAKAZE Kou"
AUTHOR_EN_NAME_ON_PROP = "WATAKAZE Kou/koÊŠ/"
AUTHOR_EN_PROP = "/watakaze koÊŠ/"
AUTHOR_IMAGE = "/static/_media/images/art/2024/ã‚ãŸã‹ãœãã‚“ã®ç‰¹å¾´ã¯ãŠãŠããªãŠã¿ã¿2024.webp"

SINCE = 2017
SITE_IMAGE = "/static/_media/icons/icon.webp"

WAVEBOX = "https://wavebox.me/wave/2l8tqqpnqjdccg85/"

ORIGIN_HOST = "cottonwind.com"
PAGES_DEV_ORIGIN = "https://cottonwind.pages.dev"

API_ORIGIN = "https://api.cottonwind.com"
API_WORKERS_ORIGIN = "https://cottonwind-api.kouwtkz.workers.dev"

API_LOCAL_ORIGIN = "http://localhost:51731"
LOCAL_ORIGIN = "http://localhost:51730"

MEDIA_ORIGIN = "https://media.cottonwind.com"

MEDIA_LOCAL_ORIGIN = "http://localhost:51731/r2"
MEDIA_WORKERS_ORIGIN = "https://cottonwind-api.kouwtkz.workers.dev/r2"

CONTACT_FORM_GOOGLE = "https://docs.google.com/forms/u/0/d/e/1FAIpQLSd-Ibgr2-Amoer3sl5pBqLbU-5H8tt7DVM7El14SkAFoeCa1g"
CONTACT_FORM_GOOGLE_DEV = "https://docs.google.com/forms/u/0/d/e/1FAIpQLSd-Ibgr2-Amoer3sl5pBqLbU-5H8tt7DVM7El14SkAFoeCa1g"

UPLOAD_BRACKET = false
UPLOAD_SERVICE = "https://f.hatena.ne.jp/kour/BlogPic/"

# RECAPTCHA_SITEKEY = "6LdVxvYpAAAAAJn93sTVrbrwLMU8GwJT2xZ3wPpn"
# RECAPTCHA_SITEKEY_DEV = "6LdVxvYpAAAAAJn93sTVrbrwLMU8GwJT2xZ3wPpn"

DISCORD_INVITE_QUESTION = "ã‚ãŸã‹ãœã‚³ã‚¦ã®ä»£ç†ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®åå‰ã¯ï¼Ÿ"
# DISCORD_INVITE_ANSWER = ""
# DISCORD_INVITE_URL = ""

# Workers env
# X_CLIENT_ID = ""
# X_CLIENT_SECRET = ""

[[vars.NAV]]
name = "home"
url = "/"

[[vars.NAV]]
name = "gallery"
url = "/gallery"

[[vars.NAV]]
name = "character"
short = "chara"
url = "/character"

[[vars.NAV]]
name = "sound"
url = "/sound"

[[vars.NAV]]
name = "links"
url = "/links"

[[vars.NAV]]
name = "works"
url = "/works"

[[vars.NAV]]
name = "about"
url = "/about"

[[vars.NAV]]
name = "setting"
url = "/setting"

[[vars.LINKS]]
mask = "#mask_twitter"
name = "ğ• (Twitter)"
url = "https://x.com/kouwtkz"

[[vars.LINKS]]
mask = "#mask_youtube"
name = "youtube"
url = "https://www.youtube.com/@kouwtkz"

[[vars.LINKS]]
mask = "#mask_pixiv"
name = "pixiv"
url = "https://www.pixiv.net/users/5577703"

[[vars.LINKS]]
mask = "#mask_instagram"
name = "instagram"
url = "https://www.instagram.com/kouwtkz/"

[[vars.LINKS]]
hidden = true
mask = "#mask_misskey_design"
name = "MisskeyDesign"
rel = "me"
row = 2
title = "Misskey design"
url = "https://misskey.design/@kouwtkz"

[[vars.LINKS]]
mask = "#mask_mascodon"
name = "Mascodon"
rel = "me"
row = 2
title = "ãƒã‚¹ã‚³ã©ã‚“ï¼"
url = "https://mascodon.jp/@kouwtkz"

[[vars.LINKS]]
mask = "#mask_bluesky"
name = "Bluesky"
rel = "me"
row = 2
url = "https://bsky.app/profile/kouwtkz.cottonwind.com"

[[vars.LINKS]]
mask = "#mask_github"
name = "GitHub"
url = "https://github.com/kouwtkz"

[[vars.LINKS]]
mask = "#mask_booth"
name = "BOOTH"
rel = "me"
row = 2
url = "https://cottonwind.booth.pm/"

[[vars.IMAGE_ALBUMS]]
name = "pickup"
[vars.IMAGE_ALBUMS.gallery.pages]
linkLabel = false
max = 4

[[vars.IMAGE_ALBUMS]]
description = "ã‚ªãƒªã‚¸ãƒŠãƒ«ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®ã‚¤ãƒ©ã‚¹ãƒˆã§ã™ï¼"
name = "art"
title = "Art List"
[vars.IMAGE_ALBUMS.gallery.pages]
[vars.IMAGE_ALBUMS.gallery.generate]
h2 = "ãƒ¡ã‚¤ãƒ³ã‚¤ãƒ©ã‚¹ãƒˆï¼"
h4 = "ã‚ªãƒªã‚¸ãƒŠãƒ«ã‚­ãƒ£ãƒ©ã®ã‚¤ãƒ©ã‚¹ãƒˆã§ã™ï¼"

[[vars.IMAGE_ALBUMS]]
description = "Blenderãªã©ã§ä½œã£ãŸ3Dãƒ¢ãƒ‡ãƒ«ã§ã™ï¼"
name = "3D"
[vars.IMAGE_ALBUMS.gallery.pages]
[vars.IMAGE_ALBUMS.gallery.generate]
h2 = "ä½œã£ãŸ3Dãƒ¢ãƒ‡ãƒ«ï¼"
h4 = "ã“ã‚Œã‹ã‚‰å¢—ã‚„ã—ãŸã„"

[[vars.IMAGE_ALBUMS]]
description = "æ¡ˆä»¶ãªã©ã®ã‚¤ãƒ©ã‚¹ãƒˆã§ã™ï¼"
name = "works"
[vars.IMAGE_ALBUMS.gallery.pages]
[vars.IMAGE_ALBUMS.gallery.generate]
h2 = "ä¾é ¼ã§æã„ãŸã‚¤ãƒ©ã‚¹ãƒˆï¼"
h4 = "ãŠä»•äº‹ä¾é ¼å—ã‘ä»˜ã‘ã¦ã¾ã™"

[[vars.IMAGE_ALBUMS]]
description = "ã‚ãŸã‹ãœã£ã“ã®ã‚ªãƒªã‚¸ãƒŠãƒ«ã‚°ãƒƒã‚ºã‚„ã‚¹ã‚¿ãƒ³ãƒ—ãªã©ã§ã™ï¼"
name = "goods"
timeFormat = "Y.m.d"
timeReplace = "released: $1"
[vars.IMAGE_ALBUMS.gallery.pages]
[vars.IMAGE_ALBUMS.gallery.generate]
h2 = "ä½œã£ãŸã‚°ãƒƒã‚ºãªã©ï¼"
h4 = "ä»Šã¯è²©å£²ã—ã¦ãªã„å ´åˆãŒã‚ã‚Šã¾ã™"

[[vars.IMAGE_ALBUMS]]
description = "ãƒ•ã‚¡ãƒ³ã‚¢ãƒ¼ãƒˆã¨ã—ã¦æã„ãŸã‚¤ãƒ©ã‚¹ãƒˆã§ã™ï¼"
name = "parody"
[vars.IMAGE_ALBUMS.gallery.pages]
max = 12
[vars.IMAGE_ALBUMS.gallery.generate]
h2 = "ãƒ‘ãƒ­ãƒ‡ã‚£ã‚¢ãƒ¼ãƒˆ"
h4 = "äºŒæ¬¡å‰µä½œãƒ•ã‚¡ãƒ³ã‚¢ãƒ¼ãƒˆã‚„ãƒ‘ãƒ­ãƒ‡ã‚£ã‚’æ²è¼‰ã—ã¦ã¾ã™ï¼"

[[vars.IMAGE_ALBUMS]]
name = "picture"
visible = {title = true, filename = false, info = true}
[vars.IMAGE_ALBUMS.gallery.pages]
max = 8
[vars.IMAGE_ALBUMS.gallery.generate]
h2 = "VRChatãªã©ã®å†™çœŸ"

[[vars.IMAGE_ALBUMS]]
name = "uploads"
[vars.IMAGE_ALBUMS.gallery.pages]
label = "other"
max = 4
[vars.IMAGE_ALBUMS.gallery.generate]
h2 = "ãã®ä»–ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰"
label = "other"

[[vars.IMAGE_ALBUMS]]
description = "æã„ã¦ãã‚ŒãŸãƒ•ã‚¡ãƒ³ã‚¢ãƒ¼ãƒˆã‚¤ãƒ©ã‚¹ãƒˆã§ã™ï¼"
name = "given"
title = "given fanart"
[vars.IMAGE_ALBUMS.gallery.pages]
hideWhenDefault = true
max = 4
[vars.IMAGE_ALBUMS.gallery.generate]
h2 = "æã„ã¦ãã‚Œã¦ã‚ã‚ŠãŒã¨ã‚ã‡ï¼"
h4 = "#ã‚ãŸã‹ãœãƒ¡çµµ"
label = "given art"

[[kv_namespaces]]
binding = "KV"
id = "c4d890a161dc4d8abc299dd09d8b3165"
preview_id = "baf0b24ce5014aa4b8fcd5a6774bc026"

[[kv_namespaces]]
binding = "NOTICE_FEED_KV"
id = "ded0df1afdc3450ca2baab60314fa9dd"

[[d1_databases]]
binding = "DB"
database_id = "8d8bef89-42a4-436d-991a-ebdbd3b252a5"
database_name = "cottonwind-db"
